crop_photo/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
   
    path('', views.photo_list,name="photo_list"),
    # path('video/', views.show_video,name="show_video"),
    
]

cropping/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.conf import settings
from django.views.static import serve
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^crop/', include('crop_photo.urls')),
]
if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

crop_photo/models.py
from django.db import models
import subprocess
import os




class Photo(models.Model):
    file = models.ImageField(upload_to='profile_picture/')
    # file = models.ImageField(upload_to='profile_picture/')
    description = models.CharField(max_length=255, blank=True)
    uploaded_at = models.DateTimeField(auto_now_add=True)

    # class Meta:
    #     verbose_name = 'photo'
    #     verbose_name_plural = 'photos'

class Video(models.Model):
    name = models.CharField(max_length=255, blank=True)
    videofile = models.FileField(upload_to='videos/')

    # def __str__(self):
    #     return self.name + ": " + str(self.videofile)
    
    def save(self):
        super().save()
        rootdir = "/home/sareena/images/videos/"
        if self.videofile.name.endswith('.mp4'):
            filename = os.path.basename(self.videofile.name)
            media_in = rootdir +filename
            media_out = rootdir+" compressed_ "+ filename
            print("passssssss")
            command = "ffmpeg  -i" + media_in + "/-vcodec libx264 -crf 22/"+ media_out+""
            # command = "ffmpeg -i " + str(media_in)+ " -vcodec libx264 -crf 22 "+ str(media_out)
            # subprocess.run("\ffmpeg -i " + "/"+filename+"/"+ " -vcodec libx264 -crf 26 "+ "/"+filename+"/")
            subprocess.run(command)
            print(command)
            super(Video,self).save()
           
           
           
           
           
           
            # print("trueee")
            # filename = os.path.basename(self.videofile.name)
            # media_in = self.videofile.path
            # media_out = rootdir + 'compressed_' + filename
            # print(self.videofile.url)
            # # subprocess.run('ffmpeg -i'+ media_in+ ' -vf scale=1280:-1 -c:v libx264 -preset veryslow -crf 22 '+ media_out)
            # # subprocess.run('ffmpeg -i '+ media_in+' -vcodec libx264 -crf 22 '+ media_out)
            # # subprocess.run("ffmpeg -i"+ filename+ "-vcodec libx264 -crf 22"+ filename)
            # subprocess.check_call(
            # ['ffmpeg', '-v', '-8', '-i', media_in +"/", '-vf', 'scale=-2:480', '-preset', 'slow',
            #  '-c:v', 'libx264', '-strict', 'experimental', '-c:a', 'aac', '-crf', '20', '-maxrate', '500k',
            #  '-bufsize', '500k', '-r', '25', '-f', 'mp4', media_out+"/", '-y'])
            # print(self.videofile.path,"1234567890")
            # super(Video,self).save()

crop_photo/forms.py
from PIL import Image
from django import forms
from django.core.files import File
from .models import Photo, Video
from io import BytesIO
import os
import subprocess




class PhotoForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput())
    y = forms.FloatField(widget=forms.HiddenInput())
    width = forms.FloatField(widget=forms.HiddenInput())
    height = forms.FloatField(widget=forms.HiddenInput())

    class Meta:
        model = Photo
        fields = ('file', 'x', 'y', 'width', 'height', )

    def save(self):
        photo = super(PhotoForm, self).save()

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        image = Image.open(photo.file)
        image.save(BytesIO(),format="jpeg" ,quality=60)
        print(image,"testt111111")
        cropped_image = image.crop((x, y, w+x, h+y))
        resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
        resized_image.save(photo.file.path)
        print(resized_image,"testt2222")
        
        

        return photo


class VideoForm(forms.ModelForm):
    

    class Meta:
        model= Video
        fields= ["name", "videofile"]
    def save(self):
        video = super(VideoForm,self).save()
        name = self.cleaned_data.get('name')
        videofile = self.cleaned_data.get('videofile')
        
        
        return video

crop_photo/views.py
from django.shortcuts import render, redirect

from .models import Photo,Video
from .forms import PhotoForm,VideoForm


def photo_list(request):
    photos = Photo.objects.all()
    videofile=Video.objects.last()
    print(videofile)
    if request.method == 'POST' and 'hidden_photo' in request.POST :
        form = PhotoForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('photo_list')

    elif request.method == 'POST' and 'hidden_video' in request.POST:
        
        form1 = VideoForm(request.POST , request.FILES )
        
        if form1.is_valid():
            print("KKKKKKKKKKKKKKKKKKKKKKK")
            
            form1.save()
            return redirect('photo_list')
    else:
        form = PhotoForm()
        form1 = VideoForm()
   
    return render(request,'crop_photo/photo_list.html', {'form': form,'form1': form1, 'photos': photos,'video': videofile})



# def show_video(request):
    
    
    

crop_photo/templates/crop_photo/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Cropping{% endblock %}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <link href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/cropper.min.js' %}"></script>
    {% block javascript %}
    {% endblock %}
  </body>
</html>

crop_photo/templates/crop_photo/photo_list.html
{% extends './base.html' %}
{%load static%}
{% block javascript %}
  <script>
    $(function () {

      /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
      $("#id_file").change(function () {
        if (this.files && this.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
            $("#image").attr("src", e.target.result);
            $("#modalCrop").modal("show");
    }
    reader.readAsDataURL(this.files[0]);
  }
      });

      /* SCRIPTS TO HANDLE THE CROPPER BOX */
      var $image = $("#image");
      var cropBoxData;
        var canvasData;
        $("#modalCrop").on("shown.bs.modal", function () {
        $image.cropper({
            viewMode: 1,
            aspectRatio: 1/1,
            minCropBoxWidth: 200,
            minCropBoxHeight: 200,
            autoCropArea: 0.65,
            //to make the crop box fixed size 
           /* strict: false,
            guides: false,
            highlight: false,
            dragCrop: false,
            cropBoxMovable: true,
            cropBoxResizable: false */
            
            ready: function () {
            $image.cropper("setCanvasData", canvasData);
            $image.cropper("setCropBoxData", cropBoxData);
            }
        });
        }).on("hidden.bs.modal", function () {
        cropBoxData = $image.cropper("getCropBoxData");
        canvasData = $image.cropper("getCanvasData");
        $image.cropper("destroy");
        });

        // Enable zoom in button
        $(".js-zoom-in").click(function () {
        $image.cropper("zoom", 0.1);
        });

        // Enable zoom out button
        $(".js-zoom-out").click(function () {
        $image.cropper("zoom", -0.1);
        });
      // ...

      /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
      $(".js-crop-and-upload").click(function () {
        var cropData = $image.cropper("getData");
        $("#id_x").val(cropData["x"]);
        $("#id_y").val(cropData["y"]);
        $("#id_height").val(cropData["height"]);
        $("#id_width").val(cropData["width"]);
        $("#formUpload").submit();
      });

    });
  </script>

  {% comment %} <script>
  /* SCRIPT TO UPLOAD VIDEO */
    $('#upload_video').click(function(){
       let files = new FormData($('#frmVideo').get(0));
        files.append('fileName', files);
        console.log(files)  
      $.ajax({
        url: "show_video", 
        type: "POST",
        data: files,
        processData: false,
        contentType: false,
        success: function (data) {
         
    
      }});

    });
  </script> {% endcomment %}


  
{% endblock %}

{% block content %}
  <!-- FORM TO UPLOAD THE IMAGES -->
  <form method="post" enctype="multipart/form-data" id="formUpload">
   <input type="hidden" name="hidden_photo">
     {% csrf_token %}
        {{ form }}
  </form>

 
    <!-- MODAL TO CROP THE IMAGE -->
<div class="modal fade" id="modalCrop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h4 class="modal-title">Crop the photo</h4>
      </div>
      <div class="modal-body">
        <img src="" id="image" style="max-width: 100%;">
      </div>
      <div class="modal-footer">
        <div class="btn-group pull-left" role="group">
          <button type="button" class="btn btn-default js-zoom-in">
            <span class="glyphicon glyphicon-zoom-in"></span>
          </button>
          <button type="button" class="btn btn-default js-zoom-out">
            <span class="glyphicon glyphicon-zoom-out"></span>
          </button>
        </div>
        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
      </div>
    </div>
  </div>
</div>


  <!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
  <div class="row" style="margin-top: 20px">
    {% for photo in photos %}

    <div class="col-sm-4 col-md-3">
          <h6>{{photo.file.name}}</h6>
          <img src="{{ photo.file.url }}" class="thumbnail"/>
    </div>
  {% endfor %}
  </div>

<hr>
<!-- FORM TO UPLOAD VIDEO -->
  <h4>Video Uploader</h4>
  <form enctype="multipart/form-data" method="POST" id="frmVideo">
  <input type="hidden" name="hidden_video">
  {% csrf_token %}
  {{ form1}}
  <button type="submit" id="upload_video" >Upload video</button>
  </form>

  
  
  <div class="row" style="margin-top: 20px">aaa
    
    {% if video %}
    <div class="container">
    <h6>{{video.videofile.name}}</h6>
      <video  width='400' controls="controls">
      <source src='{{video.videofile.url}}' type='video/mp4'>
      Your browser does not support the video tag.
      </video>
    </div>
  {% endif %}
  </div>

{% endblock %}